### ISSUE TITLE
RE2 compilation fails on Windows

### ISSUE THREAD

**Issue by wdavies973** [dukesoferl/re2#37] opened 2019-02-10 01:17 UTC
Relevant mix.exs:
`
  defp deps do  
    [  
      {:re2, "~> 1.8.6", override: true},
    ]  
  end  
`

After executing the following commands:  
`mix deps.get`  
`mix deps.compile`  

I get the following error message:
```
===> Compiling re2
'c_src' is not recognized as an internal or external command,
operable program or batch file.
===> Hook for {pc,compile} failed!

** (Mix) Could not compile dependency :re2, "escript.exe "c:/Users/Will Davies/.mix/rebar3" bare compile --paths "c:/Users/Will Davies/Desktop/roblucloudv2/_build/dev/lib/*/ebin"" command failed. You can recompile this dependency with "mix deps.compile re2", update it with "mix deps.update re2" or clean it with "mix deps.clean re2"

```

I'm using Windows 10. Erlang version 21, Elixir version 1.7.4

**Comment by tuncer** [comment] 2019-02-10 13:50
I don't have access to Windows, but I have a suspicion what might cause this. Can you try the `fix-37` branch and report back?

**Comment by wdavies973** [comment] 2019-02-10 20:46
I tried to pull the fix-37 branch with:
`{:re2, github: "matehat/cqex", branch: "fix-37"},` but it fails with:
`error: pathspec 'origin/fix-37' did not match any file(s) known to git.
** (Mix) Command "git --git-dir=.git checkout --quiet origin/fix-37" failed
` 
Any idea on how to get this working?

**Comment by tuncer** [comment] 2019-02-10 22:28
That branch exists only in https://github.com/tuncer/re2, and what you changed is just your direct dependency (`cqex`). `cqex` depends on `cqerl`, which depends on `re2` (https://github.com/matehat/cqerl/blob/master/rebar.config#L9). Unless you know of a way to tell mix to override the `re2` dependency and have it use the temporary `fix-37` branch, the quickest way to see whether the proposed fix works for you is if we try the following.

First:

```
$ git clone https://github.com/tuncer/re2
$ cd re2
$ make
```

If this actually works, despite the mix error you've encountered, then the issue is something else. However, if, as expected, this doesn't work, then:

```
$ make clean
$ git checkout fix-37
$ make
```

If this, and therefore branch `fix-37`, works, then I can cut a new release with the fix.

**Comment by tuncer** [comment] 2019-02-10 22:32
I haven't used mix and don't know if this works. But, maybe if you add `re2` explicitly in your config, it will override the transitive dependency (pulled in via `cqerl`). That way, you could specify the branch and see if it works.

**Comment by tuncer** [comment] 2019-02-11 21:05
Were you able to try the proposed solution?

**Comment by wdavies973** [comment] 2019-02-11 21:10
Not yet, I'll get back to you in a few hours.

**Comment by wdavies973** [comment] 2019-02-12 01:27
Okay, I tried this an received the same error:

[Link](https://pastebin.com/iQx0HG2A) (I had to use pastebin because it wasn't formatting here)

**Comment by tuncer** [comment] 2019-02-12 11:36
What shell are you using? Is it Visual Studio's git shell that has all the common POSIX tools?

I pushed more commits to the branch, please try again and share the output.

**Comment by wdavies973** [comment] 2019-02-12 17:19
I just ran the commands through git bash. Seems to work alright. I forgot to checkout fix-37 in the last post, so here's an updated error log, it has a few more details: 

https://pastebin.com/8ppG9kX3

**Comment by tuncer** [comment] 2019-02-12 20:27
@junyer, what's the preferred way to build RE2 on Windows? Would a mingw64 environment work, or is msvc via CMake required?

**Comment by wdavies973** [comment] 2019-02-12 21:27
I've got mingw64 if you want me to give that a go.

**Comment by tuncer** [comment] 2019-02-12 21:40
Sure, go ahead. That said, I thought the env you tried in before was a mingw64-based git and/or Visual Studio shell that has git and Microsoft's toolchain.

**Comment by junyer** [comment] 2019-02-13 12:41
https://github.com/google/re2/wiki/Install says:

> _Cygwin users: You must run CMake from the Cygwin command line, not the Windows command line._

It has been some time since I heard from anyone who did that, but I presume it still works.

**Comment by wdavies973** [comment] 2019-02-15 19:40
Sorry I've been busy with school a lot recently. Had a chance to play around with it a bit more and got some more output: https://pastebin.com/xhJj5R4z. Hopefully this will help. I'm not really sure what else to try. I don't have Cygwin or anything.

**Comment by tuncer** [comment] 2019-02-15 21:12
It appears that Microsoft's compiler must be used, and we have to first create the build script.

I don't have Windows, so I can't develop and test, but I've added commits that outline the required changes  in `c_src/build_deps.sh`. It's obviously not complete, and rebar3 won't know where to look for the RE2 build artifact it should link. However, after making `build_deps.sh` work on Windows, the only missing piece is modifying `rebar.config.script` to link the right RE2 lib (with the correct compiler settings).

We can go back and forth, and I can try to develop it, but it'd be much easier for someone to code it directly on Windows.

That said, perhaps there's an easier way to handle this.

**Comment by tuncer** [comment] 2019-02-15 21:25
@wdavies973, if you can clone https://github.com/google/re2 and then test the cmake calls, we can try to complete the changes. You have to find the right CMake invocations, based on the possibly incomplete calls in `build_deps.sh`, and then figure out where Debug and Release `re2.lib` can be found. I think we should succeed by adding a rule in `rebar.config.script` that extends `DRV_LDFLAGS` with `c_src/re2/<unknown>/re2.lib`.

**Comment by wdavies973** [comment] 2019-02-20 15:40
Working on it, it's gonna be a bit because I'm busy with a few other things at the moment.

**Comment by tuncer** [comment] 2019-02-20 15:42
Thanks

**Comment by wdavies973** [comment] 2019-02-23 17:23
Here's the output I get when making on Windows from the google repo: https://pastebin.com/JhqwyCWf

**Comment by junyer** [comment] 2019-02-24 08:43
```
./re2/re2.h:763:11: note: 'std::once_flag' is defined in header '<mutex>'; did you forget to '#include <mutex>'?
```

... and yet `re2.h` has `#include <mutex>` at line 196. I see `-std=c++11` in the compiler flags, so that answers what would have been my next question.

Digging around a bit, https://stackoverflow.com/q/14191566 looks relevant?

**Comment by tuncer** [comment] 2019-02-24 11:44
@wdavies973, did you generate the makefile with CMake? The idea is that CMake will create the right build script (mingw makefile, nmake makefile, or msvc project), and that you can use CMake to drive the build tool (nmake, make, msbuild), too, if you don't want to invoke the specific tool.

@junyer, or is the Makefile from git supposed to work out of the box on Windows?

**Comment by junyer** [comment] 2019-02-24 12:36
Well spotted, @tuncer. Cygwin, MinGW and MSYS users should prefer CMake because that's what's known to work. However, as per my last comment, the MinGW installation needs to support `<mutex>` and it appears that this one doesn't.

**Comment by wdavies973** [comment] 2019-02-26 22:25
I'll try with cmake and see what I can do.

**Comment by wdavies973** [comment] 2019-02-26 22:30
Okay I'm on branch fix-37 but there aren't any `CMakeLists.txt` so I can't run the `cmake` command.

**Comment by tuncer** [comment] 2019-02-26 22:38
You should have a checkout of RE2 in `c_src/re2`, and there should be a [`CMakeLists.txt`](https://github.com/google/re2/blob/master/CMakeLists.txt) in there. That CMake script can be used to build RE2 in environments not supported by the bundled [`Makefile`](https://github.com/google/re2/blob/master/Makefile).

The plan is for `c_src/build_deps.sh` to run CMake on Windows, not execute the regular `Makefile`.

Does that make sense? Any questions?

Check out https://github.com/google/re2/blob/master/kokoro/cmake.sh and the untested modification to use CMake here: https://github.com/dukesoferl/re2/blob/760818747ac33d8e4f8b2c9a2d0237e0cf81bbf5/c_src/build_deps.sh#L69-L81.

**Comment by tuncer** [comment] 2019-02-26 22:39
Maybe I can set up Windows CI

**Comment by tuncer** [comment] 2019-02-26 22:48
> MinGW installation needs to support `<mutex>` and it appears that this one doesn't.

@junyer, it's possible the installation is complete, but I can also imagine that it requires a different invocation or setup of some sort. From what I understand, CMake is the official way to build RE2 on Windows, correct? If that's the case, we should aim to use CMake. The main question is if mingw64 or msvc is required. Erlang is [built](https://github.com/erlang/otp/blob/master/HOWTO/INSTALL-WIN32.md) with msvc and driven by scripts run in Cygwin or MinGW. Also, RE2's kokoro scripts use CMake's "Visual Studio 14 2015" generator, so we should try to use msvc, shouldn't we?

**Comment by tuncer** [comment] 2019-02-26 23:02
@wdavies973, if things go as planned, we should have Windows CI "soon". In the meantime, your help is useful in figuring out the details.

**Comment by tuncer** [comment] 2019-02-28 21:58
I set up Linux, macOS, and Windows CI with Azure Pipelines, and turned the branch into a pull request (https://github.com/dukesoferl/re2/pull/41). @junyer, @wdavies973, let's see if we can fix the Windows build.

**Comment by tuncer** [comment] 2019-03-01 13:30
Merged #41, opened #42 for rest of the issues.

**Comment by tuncer** [comment] 2019-03-06 15:02
After fixing a bug in the rebar3 port_compiler plugin and applying further changes in re2, building and testing unit tests on Windows works. On Azure Pipelines, I could only test with Visual Studio 2017, but it ought to work with 2015 as well. I'll update the README. @wdavies973, if you use 2015 and can confirm success, I'd appreciate feedback or a README pull request. You can expect a new release on hex.pm sometime this week.

**Closed** 2019-03-06 15:19 UTC

**Comment by wdavies973** [comment] 2019-03-14 17:40
Thanks!

**Comment by wdavies973** [comment] 2019-03-21 07:00
@tuncer Looks like I'm getting a small error towards the end here: https://pastebin.com/aKhFVjgq

"c:\Program Files\erl10.1\erts-10.1\include\erl_nif.h(74): fatal error C1083: Cannot open include file: 'stdlib.h': No such file or directory"

Any idea on how to fix it?

Otherwise, your fix looks really good, it gets way farther than before and this error looks pretty easy to fix. I really appreciate your help!

**Comment by tuncer** [comment] 2019-03-21 12:30
I'll assume you have a recent CMake and also Visual Studio 2017.

In the shell, did you run `C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Auxiliary/Build/vcvars64.bat`?

Can you skip calling `make` and run `rebar3 compile` instead?

What happens if you create `hello.cc` 


```c++
#include <stdlib.h>
#include <iostream>

int main() {
    std::cout << "Hello, Windows\n";
    return 1;
}
```

and run `cl hello.cc`?

Does it make a difference to run `cl /Tp hello.cc` (see [cl options](https://docs.microsoft.com/en-us/cpp/build/reference/compiler-options-listed-alphabetically?view=vs-2017))?

If so, try this change:

```diff
diff --git a/rebar.config.script b/rebar.config.script
index 1710cf5..2e5852d 100644
--- a/rebar.config.script
+++ b/rebar.config.script
@@ -130,7 +130,7 @@ PortOpts = fun() ->
                                 [
                                  {"priv/re2_nif.so", ["c_src/re2_nif.cc"]}
                                 ]},
-                   BaseCFLAGS = "$DRV_CFLAGS -std=c++11 " ++
+                   BaseCFLAGS = "$DRV_CFLAGS /Tp -std=c++11 " ++
                         ExtraCFLAGS ++ " " ++ Flags ++ " ",
                    Hooks = [ {pre_hooks,
                               [{{pc, compile}, "sh -c c_src/build_deps.sh"}]}
```

**Comment by wdavies973** [comment] 2019-03-21 18:51
When running the the `vcvars64.bat` and then running `rebar3 compile`, I get the following error:

```
PS C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build> vcvars64.bat
**********************************************************************
** Visual Studio 2017 Developer Command Prompt v15.9.1
** Copyright (c) 2017 Microsoft Corporation
**********************************************************************
[vcvarsall.bat] Environment initialized for: 'x64'
PS C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build> cd
PS C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build> cd C:\Users\wdavi\Desktop\re2
PS C:\Users\wdavi\Desktop\re2> rebar3 compile
===> Fetching pc ({git,"https://github.com/blt/port_compiler",{tag,"v1.10.2"}})
===> Compiling pc
===> Verifying dependencies...
===> Compiling re2
'sh' is not recognized as an internal or external command,
operable program or batch file.
===> Hook for {pc,compile} failed!
```

Compiling `hello.cc` does fail with:
```
PS C:\users\wdavi\Desktop\re2> vcvars32.bat
**********************************************************************
** Visual Studio 2017 Developer Command Prompt v15.9.1
** Copyright (c) 2017 Microsoft Corporation
**********************************************************************
[vcvarsall.bat] Environment initialized for: 'x86'
PS C:\users\wdavi\Desktop\re2> cl hello.cc
Microsoft (R) C/C++ Optimizing Compiler Version 19.16.27023.1 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

hello.cc
hello.cc(1): fatal error C1034: stdlib.h: no include path set
```

I tried compiling `hello.cc` with `vcvars32.bat` and `vcvars64.bat`. 

The error is the same when running `cl /Tp hello.cc`

This error looks like it's probably something wrong with my machine and not the windows build for `re2` so if you have any advice that'd be great, but otherwise I'll just poke around with the environment variables to try to get them set correctly and maybe just reinstall visual studio.

**Comment by wdavies973** [comment] 2019-03-23 17:14
So apparently, it's not just my computer. The first error "sh" is not recognized looks like re2 isn't loading the correct compile script, since "sh" shouldn't work on Windows. I can try installing cywgin?

**Comment by tuncer** [comment] 2019-03-23 22:42
The Azure Pipelines image we use is called vs2017-win2016 (see [1](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops), [2](https://github.com/Microsoft/azure-pipelines-image-generation/blob/master/images/win/Vs2017-Server2016-Readme.md)), and the script is https://github.com/dukesoferl/re2/blob/0a025cd734381f24a728933a0d983f990542bd8a/azure-pipelines.yml#L65-L73

https://dev.azure.com/dukesoferl/re2erl/_build/results?buildId=170

**Comment by tuncer** [comment] 2019-03-23 22:42
Have you tried using the Visual Studio Git bash shortcut?

Regarding `stdlib.h`, it's unlikely but possible that you forgot to select a component during Visual Studio installation.

**Comment by wdavies973** [comment] 2019-03-24 21:09
I have tried Git bash to no avail. 

Like I said, I've also tried just a "mix deps.compile" and it throws the error with "sh" not being recognized. So it looks like when calling "mix deps.compile" it isn't loading that azure-pipelines script correctly.

**Comment by wdavies973** [comment] 2019-03-24 21:29
How can I test compiling using Cywgin?

**Comment by tuncer** [comment] 2019-03-24 22:03
> it isn't loading that azure-pipelines script correctly

That is only used by Azure Pipelines, and I linked the section to reference what invocation works on Windows. I don't know what kind of shell it is run in.

**Comment by tuncer** [comment] 2019-03-24 22:05
> I have tried Git bash to no avail

That shell, IIRC, is based on MinGW and should provide a reasonably complete environment.

**Comment by tuncer** [comment] 2019-03-24 22:19
> How can I test compiling using Cywgin?

Start Cygwin, run the vcvars64 script, then try `rebar3 compile`. I developed Windows support by relying on Azure Pipelines without access to an interactive Windows session. Tools like `rebar3`, `sh`, `cl`, `link` should all just work in a Cygwin or MinGW shell, so what you're experiencing is surprising.

**Comment by tolbrino** [comment] 2019-03-25 09:12
@tuncer @wdavies973 Just FYI, I tested the latest master and had no issues by following these steps:

- Use msys2 environment prepared with https://github.com/aeternity/aeternity/blob/master/scripts/windows/msys2_prepare.bat
- Start msys2 shell with https://github.com/aeternity/aeternity/blob/master/scripts/windows/msys2_shell.bat
- Extend `PATH` to use MSVC's `cmake`
- Run `make` and `make check`

**Comment by wdavies973** [comment] 2019-03-25 15:21
@tolbrino Is there a way to make this work with `mix`?
Or can must I compile it outside of `mix` using the above commands?

**Comment by tuncer** [comment] 2019-03-25 15:35
If @tolbrino's steps manage to provide the required environment for you, and thus you can successfully execute `make`, it means you can also run `rebar3 compile` or `mix compile`.

**Comment by tuncer** [comment] 2019-03-25 15:55
@wdavies973, if you still fail to build, want to save time, and it doesn't conflict with the rest of your development setup, you can use Ubuntu for Windows via [WSL](https://en.wikipedia.org/wiki/Windows_Subsystem_for_Linux).

**Comment by tolbrino** [comment] 2019-03-25 16:41
@wdavies973 I verified that I can build `re2` as a dep under `mix`. So I guess you could check the 2 scripts I referenced to cherry-pick some setup steps which you might be missing.

@tuncer The problem (or rather non-feature) with WSL is that you are really running a linux build environment. So if your target is win32, you will have to setup mingw64 properly in there too.

**Comment by wdavies973** [comment] 2019-04-02 02:15
@tolbrino , Good plain, works great on Ubuntu.
